#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 John Park for Adafruit Industries
#
# SPDX-License-Identifier: MIT

"""Generate src/machines/gb/gameboy_palette_gbc.h from SameBoy's Game Boy
Color boot ROM source, so the title table is extracted, never retyped.

When a Game Boy Color runs an original (DMG) cartridge, its boot ROM colours
the game from a table keyed on the cartridge title. SameBoy's open-source
boot ROM (BootROMs/cgb_boot.asm, Expat licence) reproduces that table; this
script pulls out the parts a title lookup needs:

  TitleChecksums / FirstChecksumWithDuplicate   title-byte sums to match
  PalettePerChecksum                            -> a palette combination
  Dups4thLetterArray                            tie-break on title[3]
  PaletteCombinations                           OBJ0, OBJ1, BG colour offsets
  Palettes                                      the colours, BGR555

SameBoy's own additions (its "Exclusives", reachable only by button combos
at power-on) are left out.

Usage:
  git clone https://github.com/LIJI32/SameBoy
  ./gen_gbc_palettes.py SameBoy > ../../../src/machines/gb/gameboy_palette_gbc.h
"""
import os
import re
import subprocess
import sys


def section(lines, start, end):
    """The lines after label `start`, up to label `end` (or a blank-stop)."""
    i = next(n for n, l in enumerate(lines) if l.startswith(start + ":"))
    out = []
    for l in lines[i + 1:]:
        if end and l.startswith(end + ":"):
            break
        out.append(l)
    return out


def code(l):
    return l.split(";", 1)[0].strip()


def main():
    root = sys.argv[1]
    asm_path = os.path.join(root, "BootROMs", "cgb_boot.asm")
    lines = open(asm_path).read().splitlines()
    try:
        commit = subprocess.check_output(["git", "-C", root, "rev-parse", "HEAD"],
                                         text=True).strip()
    except Exception:
        commit = "unknown"

    # Title checksums, noting where the entries needing a 4th-letter check start.
    sums, first_dup = [], None
    for l in section(lines, "TitleChecksums", "ChecksumsEnd"):
        if l.startswith("FirstChecksumWithDuplicate:"):
            first_dup = len(sums)
            continue
        m = re.match(r"db \$([0-9A-Fa-f]{2})$", code(l))
        if m:
            sums.append(int(m.group(1), 16))

    combos_for_sum = []
    for l in section(lines, "PalettePerChecksum", "Dups4thLetterArray"):
        m = re.match(r"palette_index\s+(\d+)", code(l))
        if m:
            combos_for_sum.append(int(m.group(1)))

    letters = re.search(r'db "([^"]*)"',
                        "\n".join(section(lines, "Dups4thLetterArray", "PaletteCombinations"))).group(1)

    # Combinations, as colour offsets into the flat colour list: palette_comb
    # names whole palettes (x4 colours), raw_palette_comb colour offsets.
    combos = []
    for l in section(lines, "PaletteCombinations", "Palettes"):
        if "Exclusives" in l:
            break
        c = code(l)
        m = re.match(r"(raw_palette_comb|palette_comb)\s+(.+)$", c)
        if not m or c.startswith("MACRO"):
            continue
        vals = [eval(v, {}) for v in m.group(2).split(",")]
        scale = 1 if m.group(1) == "raw_palette_comb" else 4
        combos.append([v * scale for v in vals])

    colours = []
    for l in section(lines, "Palettes", "KeyCombinationPalettes"):
        if "Exclusives" in l:
            break
        m = re.match(r"dw (.+)$", code(l))
        if m:
            colours += [int(v.strip().lstrip("$"), 16) for v in m.group(1).split(",")]

    assert first_dup is not None
    assert len(sums) == len(combos_for_sum), (len(sums), len(combos_for_sum))
    assert len(letters) == len(sums) - first_dup, (len(letters), len(sums) - first_dup)
    assert all(c < len(combos) for c in combos_for_sum)
    assert all(off + 4 <= len(colours) for c in combos for off in c)

    def rows(vals, per, fmt):
        return "\n".join("    " + " ".join(fmt(v) + "," for v in vals[i:i + per])
                         for i in range(0, len(vals), per))

    print(f"""// SPDX-FileCopyrightText: 2015-2026 Lior Halphon
//
// SPDX-License-Identifier: MIT

// GENERATED by extras/tools/gb_palettes/gen_gbc_palettes.py -- do not edit.
// Source: SameBoy BootROMs/cgb_boot.asm, commit {commit}
// (https://github.com/LIJI32/SameBoy, Expat licence).
//
// The Game Boy Color boot ROM's colour table for original Game Boy games,
// looked up by cartridge title. Included only by gameboy_palette.cpp.
#ifndef GAMEBOY_PALETTE_GBC_H
#define GAMEBOY_PALETTE_GBC_H

#include <stdint.h>

// Sum of the 16 title bytes (0x134-0x143). Entries from
// kGbcFirstDuplicate on match only if title[3] equals kGbcDupLetter.
static const uint8_t kGbcTitleSums[{len(sums)}] = {{
{rows(sums, 12, lambda v: f"0x{v:02X}")}
}};
static const unsigned kGbcFirstDuplicate = {first_dup};
static const char kGbcDupLetter[{len(letters)}] = {{
{rows(list(letters), 16, lambda v: repr(v))}
}};

// Palette combination for each entry above.
static const uint8_t kGbcComboForSum[{len(sums)}] = {{
{rows(combos_for_sum, 16, lambda v: f"{v:2d}")}
}};

// Combinations: offsets into kGbcColours of the four colours (lightest
// first) for OBJ0, OBJ1 and BG. Combination 0 is the default.
static const uint8_t kGbcCombos[{len(combos)}][3] = {{
{chr(10).join(f"    {{ {a:3d}, {b:3d}, {c:3d} }}, // {i}" for i, (a, b, c) in enumerate(combos))}
}};

// Colours, BGR555 (bits 0-4 red, 5-9 green, 10-14 blue).
static const uint16_t kGbcColours[{len(colours)}] = {{
{rows(colours, 8, lambda v: f"0x{v:04X}")}
}};

#endif""")


if __name__ == "__main__":
    main()
