// SPDX-FileCopyrightText: 2015-2026 Lior Halphon
//
// SPDX-License-Identifier: MIT

// GENERATED by extras/tools/gb_palettes/gen_gbc_palettes.py -- do not edit.
// Source: SameBoy BootROMs/cgb_boot.asm, commit 213a12ce93d66b105a113debd9396306066a7cfc
// (https://github.com/LIJI32/SameBoy, Expat licence).
//
// The Game Boy Color boot ROM's colour table for original Game Boy games,
// looked up by cartridge title. Included only by gameboy_palette.cpp.
#ifndef GAMEBOY_PALETTE_GBC_H
#define GAMEBOY_PALETTE_GBC_H

#include <stdint.h>

// Sum of the 16 title bytes (0x134-0x143). Entries from
// kGbcFirstDuplicate on match only if title[3] equals kGbcDupLetter.
static const uint8_t kGbcTitleSums[94] = {
    0x00, 0x88, 0x16, 0x36, 0xD1, 0xDB, 0xF2, 0x3C, 0x8C, 0x92, 0x3D, 0x5C,
    0x58, 0xC9, 0x3E, 0x70, 0x1D, 0x59, 0x69, 0x19, 0x35, 0xA8, 0x14, 0xAA,
    0x75, 0x95, 0x99, 0x34, 0x6F, 0x15, 0xFF, 0x97, 0x4B, 0x90, 0x17, 0x10,
    0x39, 0xF7, 0xF6, 0xA2, 0x49, 0x4E, 0x43, 0x68, 0xE0, 0x8B, 0xF0, 0xCE,
    0x0C, 0x29, 0xE8, 0xB7, 0x86, 0x9A, 0x52, 0x01, 0x9D, 0x71, 0x9C, 0xBD,
    0x5D, 0x6D, 0x67, 0x3F, 0x6B, 0xB3, 0x46, 0x28, 0xA5, 0xC6, 0xD3, 0x27,
    0x61, 0x18, 0x66, 0x6A, 0xBF, 0x0D, 0xF4, 0xB3, 0x46, 0x28, 0xA5, 0xC6,
    0xD3, 0x27, 0x61, 0x18, 0x66, 0x6A, 0xBF, 0x0D, 0xF4, 0xB3,
};
static const unsigned kGbcFirstDuplicate = 65;
static const char kGbcDupLetter[29] = {
    'B', 'E', 'F', 'A', 'A', 'R', 'B', 'E', 'K', 'E', 'K', ' ', 'R', '-', 'U', 'R',
    'A', 'R', ' ', 'I', 'N', 'A', 'I', 'L', 'I', 'C', 'E', ' ', 'R',
};

// Palette combination for each entry above.
static const uint8_t kGbcComboForSum[94] = {
     0,  4,  5, 35, 34,  3, 31, 15, 10,  5, 19, 36,  7, 37, 30, 44,
    21, 32, 31, 20,  5, 33, 13, 14,  5, 29,  5, 18,  9,  3,  2, 26,
    25, 25, 41, 42, 26, 45, 42, 45, 36, 38, 26, 42, 30, 41, 34, 34,
     5, 42,  6,  5, 33, 25, 42, 42, 40,  2, 16, 25, 42, 42,  5,  0,
    39, 36, 22, 25,  6, 32, 12, 36, 11, 39, 18, 39, 24, 31, 50, 17,
    46,  6, 27,  0, 47, 41, 41,  0,  0, 19, 34, 23, 18, 29,
};

// Combinations: offsets into kGbcColours of the four colours (lightest
// first) for OBJ0, OBJ1 and BG. Combination 0 is the default.
static const uint8_t kGbcCombos[51][3] = {
    {  16,  16, 116 }, // 0
    {  72,  72,  72 }, // 1
    {  80,  80,  80 }, // 2
    {  96,  96,  96 }, // 3
    {  36,  36,  36 }, // 4
    {   0,   0,   0 }, // 5
    { 108, 108, 108 }, // 6
    {  20,  20,  20 }, // 7
    {  48,  48,  48 }, // 8
    { 104, 104, 104 }, // 9
    {  64,  32,  32 }, // 10
    {  16, 112, 112 }, // 11
    {  16,   8,   8 }, // 12
    {  12,  16,  16 }, // 13
    {  16, 116, 116 }, // 14
    { 112,  16, 112 }, // 15
    {   8,  68,   8 }, // 16
    {  64,  64,  32 }, // 17
    {  16,  16,  28 }, // 18
    {  16,  16,  72 }, // 19
    {  16,  16,  80 }, // 20
    {  76,  76,  36 }, // 21
    {  15,  15,  44 }, // 22
    {  68,  68,   8 }, // 23
    {  16,  16,   8 }, // 24
    {  16,  16,  12 }, // 25
    { 112, 112,   0 }, // 26
    {  12,  12,   0 }, // 27
    {   0,   0,   4 }, // 28
    {  72,  88,  72 }, // 29
    {  80,  88,  80 }, // 30
    {  96,  88,  96 }, // 31
    {  64,  88,  32 }, // 32
    {  68,  16,  52 }, // 33
    { 111,   0,  56 }, // 34
    { 111,  16,  60 }, // 35
    {  76,  91,  36 }, // 36
    {  64, 112,  40 }, // 37
    {  16,  92, 112 }, // 38
    {  68,  88,   8 }, // 39
    {  16,   0,   8 }, // 40
    {  16, 112,  12 }, // 41
    { 112,  12,   0 }, // 42
    {  12, 112,  16 }, // 43
    {  84, 112,  16 }, // 44
    {  12, 112,   0 }, // 45
    { 100,  12, 112 }, // 46
    {   0, 112,  32 }, // 47
    {  16,  12, 112 }, // 48
    { 112,  12,  24 }, // 49
    {  16, 112, 116 }, // 50
};

// Colours, BGR555 (bits 0-4 red, 5-9 green, 10-14 blue).
static const uint16_t kGbcColours[120] = {
    0x7FFF, 0x32BF, 0x00D0, 0x0000, 0x639F, 0x4279, 0x15B0, 0x04CB,
    0x7FFF, 0x6E31, 0x454A, 0x0000, 0x7FFF, 0x1BEF, 0x0200, 0x0000,
    0x7FFF, 0x421F, 0x1CF2, 0x0000, 0x7FFF, 0x5294, 0x294A, 0x0000,
    0x7FFF, 0x03FF, 0x012F, 0x0000, 0x7FFF, 0x03EF, 0x01D6, 0x0000,
    0x7FFF, 0x42B5, 0x3DC8, 0x0000, 0x7E74, 0x03FF, 0x0180, 0x0000,
    0x67FF, 0x77AC, 0x1A13, 0x2D6B, 0x7ED6, 0x4BFF, 0x2175, 0x0000,
    0x53FF, 0x4A5F, 0x7E52, 0x0000, 0x4FFF, 0x7ED2, 0x3A4C, 0x1CE0,
    0x03ED, 0x7FFF, 0x255F, 0x0000, 0x036A, 0x021F, 0x03FF, 0x7FFF,
    0x7FFF, 0x01DF, 0x0112, 0x0000, 0x231F, 0x035F, 0x00F2, 0x0009,
    0x7FFF, 0x03EA, 0x011F, 0x0000, 0x299F, 0x001A, 0x000C, 0x0000,
    0x7FFF, 0x027F, 0x001F, 0x0000, 0x7FFF, 0x03E0, 0x0206, 0x0120,
    0x7FFF, 0x7EEB, 0x001F, 0x7C00, 0x7FFF, 0x3FFF, 0x7E00, 0x001F,
    0x7FFF, 0x03FF, 0x001F, 0x0000, 0x03FF, 0x001F, 0x000C, 0x0000,
    0x7FFF, 0x033F, 0x0193, 0x0000, 0x0000, 0x4200, 0x037F, 0x7FFF,
    0x7FFF, 0x7E8C, 0x7C00, 0x0000, 0x7FFF, 0x1BEF, 0x6180, 0x0000,
};

#endif
